steps:
  # Step 1: Build frontend image (context: ./frontend, Dockerfile: ../frontend.Dockerfile)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'frontend.Dockerfile',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/frontend-image',
      '.'
    ]

  # Step 2: Build backend image (context: ./backend, Dockerfile: ../Dockerfile)
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'Dockerfile',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/backend-image',
      '.'
    ]

  # Step 3: Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/frontend-image']

  # Step 4: Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/backend-image']

  # Step 5: Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'frontend-service',
        '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/frontend-image',
        '--region', 'us-central1',
        '--port', '5173',
        '--memory', '4Gi',
        '--set-env-vars', 'GOOGLE_CLOUD_PROJECT=fomc-poc,GOOGLE_CLOUD_PROJECT_NUMBER=920531840392,GOOGLE_CLOUD_LOCATION=us-central1,GOOGLE_CLOUD_BQ_DATASET=fomc-poc.920531840392,GOOGLE_CLOUD_STORAGE_BUCKET=fomc-poc,GOOGLE_GENAI_MODEL=gemini-2.0-flash,GOOGLE_GENAI_USE_VERTEXAI=1, COMMIT_SHA=manual-deploy',
        '--allow-unauthenticated'
      ]

  # Step 6: Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'backend-service',
        '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/backend-image',
        '--region', 'us-central1',
        '--port', '8080',
        '--memory', '4Gi',
        '--set-env-vars', 'GOOGLE_CLOUD_PROJECT=fomc-poc,GOOGLE_CLOUD_PROJECT_NUMBER=920531840392,GOOGLE_CLOUD_LOCATION=us-central1,GOOGLE_CLOUD_BQ_DATASET=fomc-poc.920531840392,GOOGLE_CLOUD_STORAGE_BUCKET=fomc-poc,GOOGLE_GENAI_MODEL=gemini-2.0-flash,GOOGLE_GENAI_USE_VERTEXAI=1, COMMIT_SHA=manual-deploy',
        '--allow-unauthenticated'
      ]

timeout: 1200s
